<?php

namespace Database\Seeders;

use App\Models\SidebarMenu;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class SidebarMenuSeeder extends Seeder
{
    public function run(): void
    {
        $menus = [
            [
                'title' => 'Dashboard',
                'icon' => 'mdi-view-dashboard',
                'route' => '/dashboard',
                'route_name' => 'Dashboard',
                'group_name' => null,
                'parent_menu' => null,
                'permission_slug' => 'dashboard.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Analytics Dashboard',
                'icon' => 'mdi-chart-box',
                'route' => '/dashboard-analytics',
                'route_name' => 'dashboard.analytics',
                'group_name' => null,
                'parent_menu' => null,
                'permission_slug' => 'dashboard.analytics',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Teacher Dashboard',
                'icon' => 'mdi-view-dashboard-outline',
                'route' => '/teacher-dashboard',
                'route_name' => 'teacher.dashboard',
                'group_name' => 'Teacher Portal',
                'parent_menu' => null,
                'permission_slug' => 'teacher.dashboard',
                'role_slug' => 'teacher',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Streams',
                'icon' => 'mdi-source-branch',
                'route' => '/streams',
                'route_name' => 'streams.index',
                'group_name' => 'Academic',
                'parent_menu' => 'Academic',
                'permission_slug' => 'streams.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Grades',
                'icon' => 'mdi-google-classroom',
                'route' => '/grades',
                'route_name' => 'grades.index',
                'group_name' => 'Academic',
                'parent_menu' => 'Academic',
                'permission_slug' => 'grades.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Subject Templates',
                'icon' => 'mdi-book-multiple',
                'route' => '/subject-templates',
                'route_name' => 'subject-templates',
                'group_name' => 'Academic',
                'parent_menu' => 'Academic',
                'permission_slug' => 'subjects.manage',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Subjects',
                'icon' => 'mdi-book-open-page-variant',
                'route' => '/subjects',
                'route_name' => 'subjects.index',
                'group_name' => 'Academic',
                'parent_menu' => 'Academic',
                'permission_slug' => 'subjects.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Lessons',
                'icon' => 'mdi-book-education',
                'route' => '/lessons',
                'route_name' => 'lessons.index',
                'group_name' => 'Academic',
                'parent_menu' => 'Academic',
                'permission_slug' => 'lessons.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 8,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Question Types',
                'icon' => 'mdi-format-list-bulleted-type',
                'route' => '/question-types',
                'route_name' => 'question.types',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'question.types.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 9,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Question Type Templates',
                'icon' => 'mdi-format-list-checks',
                'route' => '/question-type-templates',
                'route_name' => 'question-type-templates',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'question.types.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 10,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Questions',
                'icon' => 'mdi-help-circle',
                'route' => '/questions',
                'route_name' => 'questions.index',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'questions.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 11,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Create Question',
                'icon' => 'mdi-plus-circle',
                'route' => '/questions/create',
                'route_name' => 'questions.create',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'questions.create',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 12,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Question Approvals',
                'icon' => 'mdi-check-decagram',
                'route' => '/question-approvals',
                'route_name' => 'question.approvals',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'question.approvals',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 13,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Language Question Editor',
                'icon' => 'mdi-alphabetical',
                'route' => '/language-questions/edit',
                'route_name' => 'language.questions.edit',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'language.questions.edit',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 14,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Question Papers',
                'icon' => 'mdi-file-document-multiple',
                'route' => '/papers',
                'route_name' => 'papers.index',
                'group_name' => 'Papers',
                'parent_menu' => 'Papers',
                'permission_slug' => 'papers.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 20,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Create Paper',
                'icon' => 'mdi-file-plus',
                'route' => '/papers/creator',
                'route_name' => 'papers.creator',
                'group_name' => 'Papers',
                'parent_menu' => 'Papers',
                'permission_slug' => 'papers.create',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 21,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Paper Blueprints',
                'icon' => 'mdi-sitemap',
                'route' => '/paper-blueprints',
                'route_name' => 'paper.blueprints',
                'group_name' => 'Papers',
                'parent_menu' => 'Papers',
                'permission_slug' => 'paper.blueprints',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 22,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Paper Generator',
                'icon' => 'mdi-file-cog',
                'route' => '/paper-generator',
                'route_name' => 'paper.generator',
                'group_name' => 'Papers',
                'parent_menu' => 'Papers',
                'permission_slug' => 'papers.generate',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 23,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Teachers',
                'icon' => 'mdi-account-school',
                'route' => '/teachers',
                'route_name' => 'teachers.index',
                'group_name' => 'Teachers',
                'parent_menu' => 'Teachers',
                'permission_slug' => 'teachers.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 30,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Teacher Tasks',
                'icon' => 'mdi-clipboard-text',
                'route' => '/teacher-question-tasks',
                'route_name' => 'teacher.tasks',
                'group_name' => 'Teachers',
                'parent_menu' => 'Teachers',
                'permission_slug' => 'teacher.tasks',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 31,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Teacher Progress',
                'icon' => 'mdi-chart-line',
                'route' => '/reports/teacher-progress',
                'route_name' => 'teacher.progress',
                'group_name' => 'Reports',
                'parent_menu' => 'Reports',
                'permission_slug' => 'teacher.progress',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 32,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Teacher Analytics',
                'icon' => 'mdi-chart-box-outline',
                'route' => '/teacher-analytics',
                'route_name' => 'teacher.analytics',
                'group_name' => 'Reports',
                'parent_menu' => 'Reports',
                'permission_slug' => 'teacher.analytics',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 33,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Exam Names',
                'icon' => 'mdi-calendar-text',
                'route' => '/exam-names',
                'route_name' => 'exam.names',
                'group_name' => 'Examinations',
                'parent_menu' => 'Examinations',
                'permission_slug' => 'exam.names',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 40,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Exam Portions',
                'icon' => 'mdi-format-list-checks',
                'route' => '/exam-portions',
                'route_name' => 'exam.portions',
                'group_name' => 'Examinations',
                'parent_menu' => 'Examinations',
                'permission_slug' => 'exam.portions',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 41,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'My Question Tasks',
                'icon' => 'mdi-clipboard-check',
                'route' => '/my-question-tasks',
                'route_name' => 'teacher.my.tasks',
                'group_name' => 'Teacher Portal',
                'parent_menu' => 'Teacher Portal',
                'permission_slug' => 'teacher.my.tasks',
                'role_slug' => 'teacher',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 50,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'My Exam Portions',
                'icon' => 'mdi-book-check',
                'route' => '/my-exam-portions',
                'route_name' => 'teacher.exam.portions',
                'group_name' => 'Teacher Portal',
                'parent_menu' => 'Teacher Portal',
                'permission_slug' => 'teacher.exam.portions',
                'role_slug' => 'teacher',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 51,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Users',
                'icon' => 'mdi-account-multiple',
                'route' => '/users',
                'route_name' => 'users.index',
                'group_name' => 'Administration',
                'parent_menu' => 'Administration',
                'permission_slug' => 'users.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 60,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Roles',
                'icon' => 'mdi-shield-account',
                'route' => '/roles',
                'route_name' => 'roles.index',
                'group_name' => 'Administration',
                'parent_menu' => 'Administration',
                'permission_slug' => 'roles.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 61,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Permissions',
                'icon' => 'mdi-lock-check',
                'route' => '/permissions',
                'route_name' => 'permissions.index',
                'group_name' => 'Administration',
                'parent_menu' => 'Administration',
                'permission_slug' => 'permissions.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 62,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'SideBar Menu',
                'icon' => 'mdi-routes',
                'route' => '/sidebar-menus',
                'route_name' => 'sidebar.menus',
                'group_name' => 'Administration',
                'parent_menu' => 'Administration',
                'role_slug' => null,
                'permission_slug' => 'manage.sidebar.menus',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 63,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'App Routes',
                'icon' => 'mdi-routes',
                'route' => '/app-routes',
                'route_name' => 'app.routes',
                'group_name' => 'Administration',
                'parent_menu' => 'Administration',
                'permission_slug' => 'manage.permissions',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 64,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Security Settings',
                'icon' => 'mdi-shield-lock',
                'route' => '/security-settings',
                'route_name' => 'security.settings',
                'group_name' => 'Security',
                'parent_menu' => 'Security',
                'permission_slug' => 'security.settings',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 70,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Login Holidays',
                'icon' => 'mdi-calendar-remove',
                'route' => '/login-holidays',
                'route_name' => 'login.holidays',
                'group_name' => 'Security',
                'parent_menu' => 'Security',
                'permission_slug' => 'login.holidays',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 71,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'User Devices',
                'icon' => 'mdi-devices',
                'route' => '/user-devices',
                'route_name' => 'user.devices',
                'group_name' => 'Security',
                'parent_menu' => 'Security',
                'permission_slug' => 'user.devices',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 72,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Audit Logs',
                'icon' => 'mdi-file-search',
                'route' => '/audit-logs',
                'route_name' => 'audit.logs',
                'group_name' => 'Security',
                'parent_menu' => 'Security',
                'permission_slug' => 'audit.logs',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 73,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Import Teachers',
                'icon' => 'mdi-file-import',
                'route' => '/teachers/import',
                'route_name' => 'teachers.import',
                'group_name' => 'Imports',
                'parent_menu' => 'Imports',
                'permission_slug' => 'teachers.import',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 80,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'My Profile',
                'icon' => 'mdi-account-circle',
                'route' => '/profile',
                'route_name' => 'profile',
                'group_name' => 'Account',
                'parent_menu' => null,
                'permission_slug' => 'profile.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 90,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Blueprint Excel Import',
                'icon' => 'mdi-file-excel',
                'route' => '/blueprint-excel-import',
                'route_name' => 'blueprint.excel.import',
                'group_name' => 'Imports',
                'parent_menu' => 'Imports',
                'permission_slug' => 'paper.blueprints',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 81,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Lesson Import',
                'icon' => 'mdi-book-arrow-up',
                'route' => '/lesson-import',
                'route_name' => 'lesson.import',
                'group_name' => 'Imports',
                'parent_menu' => 'Imports',
                'permission_slug' => 'lessons.import',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 82,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],

            [
                'title' => 'Question Import',
                'icon' => 'mdi-help-box-multiple',
                'route' => '/question-import',
                'route_name' => 'question.import',
                'group_name' => 'Imports',
                'parent_menu' => 'Imports',
                'permission_slug' => 'questions.import',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 83,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Website Settings',
                'route' => '/admin/settings',
                'route_name' => 'admin.settings',
                'icon' => 'mdi-cog',
                'permission_slug' => 'settings.manage',
                'parent_id' => null,
                'group_name' => 'SaaS Management',
                'sort_order' => 900,
                'show_in_sidebar' => 1,
                'badge' => null,
                'badge_color' => null,
                'is_active' => 1,
            ],
            [
                'title' => 'Subscription Plans',
                'route' => '/admin/subscription-plans',
                'route_name' => 'admin.subscription.plans',
                'icon' => 'mdi-package-variant',
                'permission_slug' => 'subscription.plans.manage',
                'parent_id' => null,
                'group_name' => 'SaaS Management',
                'sort_order' => 500,
                'show_in_sidebar' => 1,
                'badge' => null,
                'badge_color' => null,
                'is_active' => 1,
            ],

            [
                'title' => 'Subscriptions',
                'route' => '/admin/subscriptions',
                'route_name' => 'admin.subscriptions',
                'icon' => 'mdi-card-account-details',
                'permission_slug' => 'subscriptions.view',
                'parent_id' => null,
                'group_name' => 'SaaS Management',
                'sort_order' => 501,
                'show_in_sidebar' => 1,
                'badge' => null,
                'badge_color' => null,
                'is_active' => 1,
            ],

            [
                'title' => 'Payment Transactions',
                'route' => '/admin/payment-transactions',
                'route_name' => 'admin.payment.transactions',
                'icon' => 'mdi-cash-multiple',
                'permission_slug' => 'payments.view',
                'parent_id' => null,
                'group_name' => 'SaaS Management',
                'sort_order' => 502,
                'show_in_sidebar' => 1,
                'badge' => null,
                'badge_color' => null,
                'is_active' => 1,
            ],

            [
                'title' => 'License Keys',
                'route' => '/admin/license-keys',
                'route_name' => 'admin.license.keys',
                'icon' => 'mdi-key',
                'permission_slug' => 'licenses.manage',
                'parent_id' => null,
                'group_name' => 'SaaS Management',
                'sort_order' => 503,
                'show_in_sidebar' => 1,
                'badge' => null,
                'badge_color' => null,
                'is_active' => 1,
            ],
            [
                'title' => 'SaaS Dashboard',
                'route' => '/admin/saas-dashboard',
                'route_name' => 'admin.saas.dashboard',
                'icon' => 'mdi-view-dashboard-variant',
                'permission_slug' => 'saas.dashboard',
                'group_name' => 'SaaS Management',
                'sort_order' => 498,
                'show_in_sidebar' => 1,
                'is_active' => 1,
            ],
            [
                'title' => 'Create User',
                'route' => '/users/create',
                'route_name' => 'users.create',
                'group_name' => 'Administration',
                'permission_slug' => 'users.create',
                'sort_order' => 59,
                'show_in_sidebar' => 1,
                'is_active' => 1,
            ],
            [
                'title' => 'Demo Enquiries',
                'route' => '/admin/demo-enquiries',
                'route_name' => 'admin.demo.enquiries',
                'permission_slug' => 'demo.enquiries.view',
                'group_name' => 'SaaS Management',
                'sort_order' => 499,
                'show_in_sidebar' => 1,
                'is_active' => 1,
            ],
            [
                'parent_id' => null,
                'title' => 'Proposals',
                'icon' => 'mdi-file-document-outline',
                'route' => '/admin/proposals',
                'route_name' => 'admin.proposals',
                'group_name' => 'CRM & Billing',
                'parent_menu' => null,
                'permission_slug' => 'proposals.view',
                'feature_key' => null,
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 81,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'parent_id' => null,
                'title' => 'Quotations',
                'icon' => 'mdi-file-percent-outline',
                'route' => '/admin/quotations',
                'route_name' => 'admin.quotations',
                'group_name' => 'CRM & Billing',
                'parent_menu' => null,
                'permission_slug' => 'quotations.view',
                'feature_key' => null,
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 82,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'parent_id' => null,
                'title' => 'Invoices',
                'icon' => 'mdi-receipt-text-outline',
                'route' => '/admin/invoices',
                'route_name' => 'admin.invoices',
                'group_name' => 'CRM & Billing',
                'parent_menu' => null,
                'permission_slug' => 'invoices.view',
                'feature_key' => null,
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 83,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'parent_id' => null,
                'title' => 'CRM Dashboard',
                'icon' => 'mdi-view-dashboard-outline',
                'route' => '/admin/crm-dashboard',
                'route_name' => 'admin.crm.dashboard',
                'group_name' => 'CRM & Billing',
                'parent_menu' => null,
                'permission_slug' => 'proposals.view',
                'feature_key' => null,
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 80,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'parent_id' => null,
                'title' => 'Proposal Templates',
                'icon' => 'mdi-file-cog-outline',
                'route' => '/admin/proposal-templates',
                'route_name' => 'admin.proposal.templates',
                'group_name' => 'CRM & Billing',
                'parent_menu' => null,
                'permission_slug' => 'proposals.create',
                'feature_key' => null,
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 80,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Premium Question Bank',
                'icon' => 'mdi-database-search',
                'route' => '/master-question-bank',
                'route_name' => 'master-question-bank.questions',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'premium.question.bank.view',
                'feature_key' => 'premium_question_bank',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 15,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Question Bank Packages',
                'icon' => 'mdi-package-variant-closed',
                'route' => '/admin/question-bank-packages',
                'route_name' => 'admin.question-bank-packages.index',
                'group_name' => 'SaaS Management',
                'parent_menu' => 'SaaS Management',
                'permission_slug' => 'question.bank.packages.manage',
                'feature_key' => 'saas_management',
                'role_slug' => 'superadmin',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 504,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Master Questions',
                'icon' => 'mdi-database-edit',
                'route' => '/admin/master-questions',
                'route_name' => 'admin.master-questions.index',
                'group_name' => 'SaaS Management',
                'parent_menu' => 'SaaS Management',
                'permission_slug' => 'master.questions.manage',
                'feature_key' => 'saas_management',
                'role_slug' => 'superadmin',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 505,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Question Bank Purchases',
                'icon' => 'mdi-cart-check',
                'route' => '/admin/question-bank-purchases',
                'route_name' => 'admin.question-bank-purchases.index',
                'group_name' => 'SaaS Management',
                'parent_menu' => 'SaaS Management',
                'permission_slug' => 'question.bank.purchases.manage',
                'feature_key' => 'saas_management',
                'role_slug' => 'superadmin',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 506,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'AI Paper Generator',
                'icon' => 'mdi-robot',
                'route' => '/paper-generator/ai',
                'route_name' => 'ai.paper.generator.index',
                'group_name' => 'Papers',
                'parent_menu' => 'Papers',
                'permission_slug' => 'ai.paper.generator.index',
                'feature_key' => 'ai_paper_generator',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 315,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'AI Paper Generator',
                'icon' => 'mdi-robot',
                'route' => '/admin/ai-paper-generations',
                'route_name' => 'admin.ai-paper-generations.index',
                'group_name' => 'Question Papers',
                'parent_menu' => 'Question Papers',
                'permission_slug' => 'admin.ai.paper.generator.manage',
                'feature_key' => 'ai_paper_generator',
                'role_slug' => 'superadmin',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 610,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            
            



        ];

        $featureKeys = [
            // Academic
            'streams.index' => 'academic_setup',
            'grades.index' => 'academic_setup',
            'grades.status' => 'academic_setup',
            'subjects.index' => 'academic_setup',
            'subjects.status' => 'academic_setup',
            'subject-templates' => 'academic_setup',
            'subject-templates.apply' => 'academic_setup',
            'lessons.index' => 'academic_setup',

            // Question Bank
            'question.types' => 'question_bank',
            'question-type-templates' => 'question_bank',
            'question-type-templates.apply' => 'question_bank',
            'questions.index' => 'question_bank',
            'questions.create' => 'question_bank',
            'questions.show' => 'question_bank',
            'questions.edit' => 'question_bank',
            'questions.delete' => 'question_bank',
            'language.questions.edit' => 'question_bank',
            'language.questions.group' => 'question_bank',

            // Approval Workflow
            'question.approvals' => 'approval_workflow',
            'question.approvals.approve' => 'approval_workflow',
            'question.approvals.reject' => 'approval_workflow',

            // Manual Paper Creation
            'papers.index' => 'manual_paper_creation',
            'papers.create' => 'manual_paper_creation',
            'papers.creator' => 'manual_paper_creation',
            'paper.edit' => 'manual_paper_creation',
            'papers.delete' => 'manual_paper_creation',
            'question.paper.view' => 'manual_paper_creation',
            'question-papers.pdf' => 'manual_paper_creation',
            'question-papers.finalize' => 'manual_paper_creation',
            'question-papers.reopen' => 'manual_paper_creation',
            'question-papers.printed' => 'manual_paper_creation',
            'question-papers.archive' => 'manual_paper_creation',

            // Blueprint Management
            'paper.blueprints' => 'blueprint_management',
            'paper.blueprints.dropdown' => 'blueprint_management',
            'paper.blueprints.status' => 'blueprint_management',
            'paper.blueprints.copy' => 'blueprint_management',

            // Auto Paper Generator
            'paper.generator' => 'auto_paper_generator',
            'paper.generator.preview' => 'auto_paper_generator',
            'paper.generator.generate' => 'auto_paper_generator',
            'papers.auto-generate' => 'auto_paper_generator',
            'papers.generate-from-blueprint' => 'auto_paper_generator',
            'papers.generate' => 'auto_paper_generator',

            // Teacher Management
            'teachers.index' => 'teacher_management',
            'teachers.create' => 'teacher_management',
            'teachers.show' => 'teacher_management',
            'teachers.update' => 'teacher_management',
            'teachers.destroy' => 'teacher_management',
            'users.index' => 'teacher_management',
            'users.create' => 'teacher_management',
            'users.permissions' => 'teacher_management',
            'users.permissions.sync' => 'teacher_management',
            'users.bulk-login-access' => 'teacher_management',

            // Teacher Tasks
            'teacher.tasks' => 'teacher_tasks',
            'teacher.my.tasks' => 'teacher_tasks',

            // Exam Portion
            'exam.names' => 'exam_portion',
            'exam-names.status' => 'exam_portion',
            'exam.portions' => 'exam_portion',
            'exam-portions.submit' => 'exam_portion',
            'exam-portions.approve' => 'exam_portion',
            'exam-portions.reject' => 'exam_portion',
            'teacher.exam.portions' => 'exam_portion',

            // Reports / Analytics
            'teacher.progress' => 'basic_reports',
            'teacher.analytics' => 'analytics',
            'dashboard.analytics' => 'analytics',

            // Imports / Exports
            'teachers.import' => 'import_export',
            'teachers.import.preview' => 'import_export',
            'teachers.import.template' => 'import_export',
            'lesson.import' => 'import_export',
            'lesson.import.template' => 'import_export',
            'question.import' => 'import_export',
            'question.import.template' => 'import_export',
            'question-types.import' => 'import_export',
            'blueprint.excel.import' => 'import_export',
            'blueprint.import.question-type-template' => 'import_export',
            'blueprint.import.paper-blueprint' => 'import_export',
            'blueprint.import.all' => 'import_export',
            'blueprint.excel' => 'import_export',

            // Security
            'security.settings' => 'advanced_security',
            'login.holidays' => 'advanced_security',
            'user.devices' => 'advanced_security',
            'user-devices.index' => 'advanced_security',
            'user-devices.trust' => 'advanced_security',
            'user-devices.block' => 'advanced_security',
            'user-devices.destroy' => 'advanced_security',
            'audit.logs' => 'advanced_security',

            // SaaS Management
            'admin.saas.dashboard' => 'saas_management',
            'admin.subscription.plans' => 'saas_management',
            'admin.subscriptions' => 'saas_management',
            'admin.payment.transactions' => 'saas_management',
            'admin.license.keys' => 'saas_management',
            'admin.settings' => 'saas_management',
            'admin.demo.enquiries' => 'saas_management',

            // CRM & Billing
            'admin.crm.dashboard' => 'crm',
            'admin.proposals' => 'crm',
            'admin.proposals.create' => 'crm',
            'admin.proposals.edit' => 'crm',
            'admin.proposals.preview' => 'crm',
            'admin.proposal.templates' => 'crm',
            'admin.proposal.templates.create' => 'crm',
            'admin.proposal.templates.edit' => 'crm',
            'admin.quotations' => 'crm',
            'admin.quotations.edit' => 'crm',
            'admin.invoices' => 'crm',
            'admin.invoices.edit' => 'crm',

            //Master Question Bank
            'master-question-bank.packages' => 'premium_question_bank',
            'master-question-bank.questions' => 'premium_question_bank',
            'master-question-bank.import' => 'premium_question_bank',

            'admin.question-bank-packages.index' => 'saas_management',
            'admin.master-questions.index' => 'saas_management',
            'admin.question-bank-purchases.index' => 'saas_management',
        ];

        foreach ($menus as $menu) {
            $routeName = $menu['route_name'];

            if (array_key_exists($routeName, $featureKeys)) {
                $menu['feature_key'] = $featureKeys[$routeName];
            } elseif (! array_key_exists('feature_key', $menu)) {
                $menu['feature_key'] = null;
            }

            $payload = [];

            foreach ($menu as $column => $value) {
                if (Schema::hasColumn('sidebar_menus', $column)) {
                    $payload[$column] = $value;
                }
            }

            SidebarMenu::updateOrCreate(
                ['route_name' => $routeName],
                $payload
            );
        }

        $existingRouteNames = collect($menus)
            ->pluck('route_name')
            ->filter()
            ->all();

        foreach ($featureKeys as $routeName => $featureKey) {
            if (in_array($routeName, $existingRouteNames, true)) {
                continue;
            }

            $payload = [
                'title' => str($routeName)->replace(['.', '-'], ' ')->title()->toString(),
                'route_name' => $routeName,
                'feature_key' => $featureKey,
                'permission_slug' => null,
                'role_slug' => null,
                'is_active' => true,
                'show_in_sidebar' => false,
            ];

            $safePayload = [];

            foreach ($payload as $column => $value) {
                if (Schema::hasColumn('sidebar_menus', $column)) {
                    $safePayload[$column] = $value;
                }
            }

            SidebarMenu::updateOrCreate(
                ['route_name' => $routeName],
                $safePayload
            );
        }
    }
}
