<?php

namespace Database\Seeders;

use App\Models\SidebarMenu;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class SidebarMenuSeeder extends Seeder
{
    public function run(): void
    {
        $menus = [
            [
                'title' => 'Dashboard',
                'icon' => 'mdi-view-dashboard',
                'route' => '/dashboard',
                'route_name' => 'Dashboard',
                'group_name' => null,
                'parent_menu' => null,
                'permission_slug' => 'dashboard.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 1,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Analytics Dashboard',
                'icon' => 'mdi-chart-box',
                'route' => '/dashboard-analytics',
                'route_name' => 'dashboard.analytics',
                'group_name' => null,
                'parent_menu' => null,
                'permission_slug' => 'dashboard.analytics',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 2,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Teacher Dashboard',
                'icon' => 'mdi-view-dashboard-outline',
                'route' => '/teacher-dashboard',
                'route_name' => 'teacher.dashboard',
                'group_name' => 'Teacher Portal',
                'parent_menu' => null,
                'permission_slug' => 'teacher.dashboard',
                'role_slug' => 'teacher',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 3,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Streams',
                'icon' => 'mdi-source-branch',
                'route' => '/streams',
                'route_name' => 'streams.index',
                'group_name' => 'Academic',
                'parent_menu' => 'Academic',
                'permission_slug' => 'streams.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 4,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Grades',
                'icon' => 'mdi-google-classroom',
                'route' => '/grades',
                'route_name' => 'grades.index',
                'group_name' => 'Academic',
                'parent_menu' => 'Academic',
                'permission_slug' => 'grades.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 5,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Subject Templates',
                'icon' => 'mdi-book-multiple',
                'route' => '/subject-templates',
                'route_name' => 'subject-templates',
                'group_name' => 'Academic',
                'parent_menu' => 'Academic',
                'permission_slug' => 'subjects.manage',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 6,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Subjects',
                'icon' => 'mdi-book-open-page-variant',
                'route' => '/subjects',
                'route_name' => 'subjects.index',
                'group_name' => 'Academic',
                'parent_menu' => 'Academic',
                'permission_slug' => 'subjects.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 7,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Lessons',
                'icon' => 'mdi-book-education',
                'route' => '/lessons',
                'route_name' => 'lessons.index',
                'group_name' => 'Academic',
                'parent_menu' => 'Academic',
                'permission_slug' => 'lessons.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 8,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Question Types',
                'icon' => 'mdi-format-list-bulleted-type',
                'route' => '/question-types',
                'route_name' => 'question.types',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'question.types.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 9,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Question Type Templates',
                'icon' => 'mdi-format-list-checks',
                'route' => '/question-type-templates',
                'route_name' => 'question-type-templates',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'question.types.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 10,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Questions',
                'icon' => 'mdi-help-circle',
                'route' => '/questions',
                'route_name' => 'questions.index',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'questions.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 11,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Create Question',
                'icon' => 'mdi-plus-circle',
                'route' => '/questions/create',
                'route_name' => 'questions.create',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'questions.create',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 12,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Question Approvals',
                'icon' => 'mdi-check-decagram',
                'route' => '/question-approvals',
                'route_name' => 'question.approvals',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'question.approvals',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 13,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Language Question Editor',
                'icon' => 'mdi-alphabetical',
                'route' => '/language-questions/edit',
                'route_name' => 'language.questions.edit',
                'group_name' => 'Question Bank',
                'parent_menu' => 'Question Bank',
                'permission_slug' => 'language.questions.edit',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 14,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Question Papers',
                'icon' => 'mdi-file-document-multiple',
                'route' => '/papers',
                'route_name' => 'papers.index',
                'group_name' => 'Papers',
                'parent_menu' => 'Papers',
                'permission_slug' => 'papers.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 20,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Create Paper',
                'icon' => 'mdi-file-plus',
                'route' => '/papers/creator',
                'route_name' => 'papers.creator',
                'group_name' => 'Papers',
                'parent_menu' => 'Papers',
                'permission_slug' => 'papers.create',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 21,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Paper Blueprints',
                'icon' => 'mdi-sitemap',
                'route' => '/paper-blueprints',
                'route_name' => 'paper.blueprints',
                'group_name' => 'Papers',
                'parent_menu' => 'Papers',
                'permission_slug' => 'paper.blueprints',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 22,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Paper Generator',
                'icon' => 'mdi-file-cog',
                'route' => '/paper-generator',
                'route_name' => 'paper.generator',
                'group_name' => 'Papers',
                'parent_menu' => 'Papers',
                'permission_slug' => 'papers.generate',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 23,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Teachers',
                'icon' => 'mdi-account-school',
                'route' => '/teachers',
                'route_name' => 'teachers.index',
                'group_name' => 'Teachers',
                'parent_menu' => 'Teachers',
                'permission_slug' => 'teachers.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 30,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Teacher Tasks',
                'icon' => 'mdi-clipboard-text',
                'route' => '/teacher-question-tasks',
                'route_name' => 'teacher.tasks',
                'group_name' => 'Teachers',
                'parent_menu' => 'Teachers',
                'permission_slug' => 'teacher.tasks',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 31,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Teacher Progress',
                'icon' => 'mdi-chart-line',
                'route' => '/reports/teacher-progress',
                'route_name' => 'teacher.progress',
                'group_name' => 'Reports',
                'parent_menu' => 'Reports',
                'permission_slug' => 'teacher.progress',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 32,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Teacher Analytics',
                'icon' => 'mdi-chart-box-outline',
                'route' => '/teacher-analytics',
                'route_name' => 'teacher.analytics',
                'group_name' => 'Reports',
                'parent_menu' => 'Reports',
                'permission_slug' => 'teacher.analytics',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 33,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Exam Names',
                'icon' => 'mdi-calendar-text',
                'route' => '/exam-names',
                'route_name' => 'exam.names',
                'group_name' => 'Examinations',
                'parent_menu' => 'Examinations',
                'permission_slug' => 'exam.names',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 40,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Exam Portions',
                'icon' => 'mdi-format-list-checks',
                'route' => '/exam-portions',
                'route_name' => 'exam.portions',
                'group_name' => 'Examinations',
                'parent_menu' => 'Examinations',
                'permission_slug' => 'exam.portions',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 41,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'My Question Tasks',
                'icon' => 'mdi-clipboard-check',
                'route' => '/my-question-tasks',
                'route_name' => 'teacher.my.tasks',
                'group_name' => 'Teacher Portal',
                'parent_menu' => 'Teacher Portal',
                'permission_slug' => 'teacher.my.tasks',
                'role_slug' => 'teacher',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 50,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'My Exam Portions',
                'icon' => 'mdi-book-check',
                'route' => '/my-exam-portions',
                'route_name' => 'teacher.exam.portions',
                'group_name' => 'Teacher Portal',
                'parent_menu' => 'Teacher Portal',
                'permission_slug' => 'teacher.exam.portions',
                'role_slug' => 'teacher',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 51,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Users',
                'icon' => 'mdi-account-multiple',
                'route' => '/users',
                'route_name' => 'users.index',
                'group_name' => 'Administration',
                'parent_menu' => 'Administration',
                'permission_slug' => 'users.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 60,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Roles',
                'icon' => 'mdi-shield-account',
                'route' => '/roles',
                'route_name' => 'roles.index',
                'group_name' => 'Administration',
                'parent_menu' => 'Administration',
                'permission_slug' => 'roles.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 61,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Permissions',
                'icon' => 'mdi-lock-check',
                'route' => '/permissions',
                'route_name' => 'permissions.index',
                'group_name' => 'Administration',
                'parent_menu' => 'Administration',
                'permission_slug' => 'permissions.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 62,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'SideBar Menu',
                'icon' => 'mdi-routes',
                'route' => '/sidebar-menus',
                'route_name' => 'sidebar.menus',
                'group_name' => 'Administration',
                'parent_menu' => 'Administration',
                'role_slug' => 'admin',
                'permission_slug' => 'manage.sidebar.menus',
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 63,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'App Routes',
                'icon' => 'mdi-routes',
                'route' => '/app-routes',
                'route_name' => 'app.routes',
                'group_name' => 'Administration',
                'parent_menu' => 'Administration',
                'permission_slug' => 'manage.permissions',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 64,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Security Settings',
                'icon' => 'mdi-shield-lock',
                'route' => '/security-settings',
                'route_name' => 'security.settings',
                'group_name' => 'Security',
                'parent_menu' => 'Security',
                'permission_slug' => 'security.settings',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 70,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Login Holidays',
                'icon' => 'mdi-calendar-remove',
                'route' => '/login-holidays',
                'route_name' => 'login.holidays',
                'group_name' => 'Security',
                'parent_menu' => 'Security',
                'permission_slug' => 'login.holidays',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 71,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'User Devices',
                'icon' => 'mdi-devices',
                'route' => '/user-devices',
                'route_name' => 'user.devices',
                'group_name' => 'Security',
                'parent_menu' => 'Security',
                'permission_slug' => 'user.devices',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 72,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Audit Logs',
                'icon' => 'mdi-file-search',
                'route' => '/audit-logs',
                'route_name' => 'audit.logs',
                'group_name' => 'Security',
                'parent_menu' => 'Security',
                'permission_slug' => 'audit.logs',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 73,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Import Teachers',
                'icon' => 'mdi-file-import',
                'route' => '/teachers/import',
                'route_name' => 'teachers.import',
                'group_name' => 'Imports',
                'parent_menu' => 'Imports',
                'permission_slug' => 'teachers.import',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 80,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'My Profile',
                'icon' => 'mdi-account-circle',
                'route' => '/profile',
                'route_name' => 'profile',
                'group_name' => 'Account',
                'parent_menu' => null,
                'permission_slug' => 'profile.view',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 90,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Blueprint Excel Import',
                'icon' => 'mdi-file-excel',
                'route' => '/blueprint-excel-import',
                'route_name' => 'blueprint.excel.import',
                'group_name' => 'Imports',
                'parent_menu' => 'Imports',
                'permission_slug' => 'paper.blueprints',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 81,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Lesson Import',
                'icon' => 'mdi-book-arrow-up',
                'route' => '/lesson-import',
                'route_name' => 'lesson.import',
                'group_name' => 'Imports',
                'parent_menu' => 'Imports',
                'permission_slug' => 'lessons.import',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 82,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],

            [
                'title' => 'Question Import',
                'icon' => 'mdi-help-box-multiple',
                'route' => '/question-import',
                'route_name' => 'question.import',
                'group_name' => 'Imports',
                'parent_menu' => 'Imports',
                'permission_slug' => 'questions.import',
                'role_slug' => null,
                'badge' => null,
                'badge_color' => null,
                'sort_order' => 83,
                'is_active' => true,
                'show_in_sidebar' => true,
            ],
            [
                'title' => 'Website Settings',
                'route' => '/admin/settings',
                'route_name' => 'admin.settings',
                'icon' => 'mdi-cog',
                'permission_slug' => 'settings.manages',
                'parent_id' => null,
                'group_name' => 'SaaS Management',
                'sort_order' => 900,
                'show_in_sidebar' => 1,
                'badge' => null,
                'badge_color' => null,
                'is_active' => 1,
            ],
            [
                'title' => 'Subscription Plans',
                'route' => '/admin/subscription-plans',
                'route_name' => 'admin.subscription.plans',
                'icon' => 'mdi-package-variant',
                'permission_slug' => 'subscription.plans.manage',
                'parent_id' => null,
                'group_name' => 'SaaS Management',
                'sort_order' => 500,
                'show_in_sidebar' => 1,
                'badge' => null,
                'badge_color' => null,
                'is_active' => 1,
            ],

            [
                'title' => 'Subscriptions',
                'route' => '/admin/subscriptions',
                'route_name' => 'admin.subscriptions',
                'icon' => 'mdi-card-account-details',
                'permission_slug' => 'subscriptions.view',
                'parent_id' => null,
                'group_name' => 'SaaS Management',
                'sort_order' => 501,
                'show_in_sidebar' => 1,
                'badge' => null,
                'badge_color' => null,
                'is_active' => 1,
            ],

            [
                'title' => 'Payment Transactions',
                'route' => '/admin/payment-transactions',
                'route_name' => 'admin.payment.transactions',
                'icon' => 'mdi-cash-multiple',
                'permission_slug' => 'payments.view',
                'parent_id' => null,
                'group_name' => 'SaaS Management',
                'sort_order' => 502,
                'show_in_sidebar' => 1,
                'badge' => null,
                'badge_color' => null,
                'is_active' => 1,
            ],

            [
                'title' => 'License Keys',
                'route' => '/admin/license-keys',
                'route_name' => 'admin.license.keys',
                'icon' => 'mdi-key',
                'permission_slug' => 'licenses.manage',
                'parent_id' => null,
                'group_name' => 'SaaS Management',
                'sort_order' => 503,
                'show_in_sidebar' => 1,
                'badge' => null,
                'badge_color' => null,
                'is_active' => 1,
            ],
            [
                'title' => 'SaaS Dashboard',
                'route' => '/admin/saas-dashboard',
                'route_name' => 'admin.saas.dashboard',
                'icon' => 'mdi-view-dashboard-variant',
                'permission_slug' => 'saas.dashboard',
                'group_name' => 'SaaS Management',
                'sort_order' => 498,
                'show_in_sidebar' => 1,
                'is_active' => 1,
            ],
            [
                'title' => 'Create User',
                'route' => '/users/create',
                'route_name' => 'users.create',
                'group_name' => 'Administration',
                'permission_slug' => 'users.create',
                'sort_order' => 59,
                'show_in_sidebar' => 1,
                'is_active' => 1,
            ],
            [
                'title' => 'Demo Enquiries',
                'route' => '/admin/demo-enquiries',
                'route_name' => 'admin.demo.enquiries',
                'permission_slug' => 'demo.enquiries.view',
                'group_name' => 'SaaS Management',
                'sort_order' => 499,
                'show_in_sidebar' => 1,
                'is_active' => 1,
            ]



        ];

        $featureKeys = [
            'streams.index' => 'academic_setup',
            'grades.index' => 'academic_setup',
            'subjects.index' => 'academic_setup',
            'subject-templates' => 'academic_setup',
            'lessons.index' => 'academic_setup',

            'question.types' => 'question_bank',
            'question-type-templates' => 'question_bank',
            'questions.index' => 'question_bank',
            'questions.create' => 'question_bank',
            'language.questions.edit' => 'question_bank',

            'question.approvals' => 'approval_workflow',

            'papers.index' => 'manual_paper_creation',
            'papers.creator' => 'manual_paper_creation',

            'paper.blueprints' => 'blueprint_management',

            'paper.generator' => 'auto_paper_generator',
            'papers.generate' => 'auto_paper_generator',

            'teachers.index' => 'teacher_management',

            'teacher.tasks' => 'teacher_tasks',
            'teacher.my.tasks' => 'teacher_tasks',

            'exam.names' => 'exam_portion',
            'exam.portions' => 'exam_portion',
            'teacher.exam.portions' => 'exam_portion',

            'teacher.progress' => 'basic_reports',

            'teacher.analytics' => 'analytics',
            'dashboard.analytics' => 'analytics',

            'teachers.import' => 'import_export',
            'lesson.import' => 'import_export',
            'question.import' => 'import_export',
            'blueprint.excel.import' => 'import_export',

            'security.settings' => 'advanced_security',
            'login.holidays' => 'advanced_security',
            'user.devices' => 'advanced_security',
            'audit.logs' => 'advanced_security',

            'admin.saas.dashboard' => 'saas_management',
            'admin.subscription.plans' => 'saas_management',
            'admin.subscriptions' => 'saas_management',
            'admin.payment.transactions' => 'saas_management',
            'admin.license.keys' => 'saas_management',
            'admin.settings' => 'saas_management',
        ];

        foreach ($menus as $menu) {
            $payload = [];

            foreach ($menu as $column => $value) {
                if (Schema::hasColumn('sidebar_menus', $column)) {
                    $payload[$column] = $value;
                }
            }

            SidebarMenu::updateOrCreate(
                ['route_name' => $menu['route_name']],
                $payload
            );
        }
    }
}
